[package]
name = "autd3-emulator-server"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autd3-core = "1.9.3"
vecmath = "1.0.0"
