[package]
name = "autd-emulator"
version = "0.2.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acoustic_field_viewer = {path="../acoustic_field_viewer"}
conrod = "0.62.1"
conrod_core = "0.74.0"
conrod_piston = "0.74.0"
camera_controllers = "0.32.0"
find_folder = "0.3.0"
piston_window = "0.120.0"
quaternion = "0.4.1"
scarlet = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vecmath = "1.0.0"
vecmath_util = {path="../vecmath_util"}
autd3-core = "1.5.0"
