name: build

on:
  push:
    tags-ignore:
      - v*
    branches:
      - 'dev'

jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: Build
      run: cargo build --workspace --verbose --all-features
    - name: Run tests
      run: cargo test --workspace --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive
    - name: lint
      run: cargo clippy --all-targets --all-features -- -D warnings